(function(g){var window=this;var Jya=function(a,b){return g.Vb(a,b)},d6=function(a){g.qm(a,"zx",g.Va());
return a},e6=function(a,b,c){g.xa(c)||(c=[String(c)]);
g.tm(a.g,b,c)},Kya=function(a,b){var c=[];
g.Zi(b,function(a){try{var b=g.QC.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.PC(b)&&c.push(a):c.push(a)},a);
return c},Lya=function(a,b){var c=Kya(a,b);
(0,g.G)(c,function(a){g.QC.prototype.remove.call(this,a)},a)},Mya=function(){var a=g.JG;
Lya(a,a.g.Xd(!0))},Nya=function(a,b,c,d){var e=new g.hm(null,void 0);
a&&g.im(e,a);b&&g.jm(e,b);c&&g.km(e,c);d&&g.lm(e,d);return e},Oya=function(a){g.bG[a]&&(a=g.bG[a],(0,g.G)(a,function(a){g.$F[a]&&delete g.$F[a]}),a.length=0)},Pya=function(a){var b=g.ZF();
if(b)if(b.clear(a),a)Oya(a);else for(var c in g.bG)Oya(c)},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.A=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.bm;this.g=this.o="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Qya(this,a.capabilities||""),Rya(this,a.experiments||""),this.o=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},Qya=function(a,b){a.capabilities.clear();
(0,g.Jd)(b.split(","),g.Da(Jya,Sya)).forEach(function(b){a.capabilities.add(b)})},Rya=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Tya=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Uya=function(a){return new g6(a)},Vya=function(a){return g.xa(a)?(0,g.H)(a,Uya):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return g.xa(a)?"["+(0,g.H)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Wya=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},l6=function(a,b){return g.fb(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},m6=function(a,b){return g.fb(a,function(a){return h6(a,b)})},n6=function(){var a=g.MG("yt-remote-connected-devices")||[];
g.Eb(a);return a},Xya=function(a){if(g.ob(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.H)(a,function(a,b){return 0==b?a:a.substring(c.length)})},Yya=function(a){g.LG("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.MG("yt-remote-device-id");a||(a=k6(),g.LG("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.kb(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.kb(a,b);g.RG()&&g.Gb(a,b);a=Xya(a);if(g.ob(a))try{g.PG.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.QG("remote_sid",a.join(","),-1)}catch(c){}},Zya=function(){return g.MG("yt-remote-session-browser-channel")},$ya=function(){return g.MG("yt-remote-local-screens")||[]},aza=function(){g.LG("yt-remote-lounge-token-expiration",!0,86400)},bza=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.H)($ya(),function(a){return a.loungeToken}),c=(0,g.H)(a,function(a){return a.loungeToken});
(0,g.Pl)(c,function(a){return!g.kb(b,a)})&&aza();
g.LG("yt-remote-local-screens",a,31536E3)},cza=function(a,b){g.LG("yt-remote-session-browser-channel",a);
g.LG("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.kb(c,d)||c.push(d);Yya(c);q6()},r6=function(a){a||(g.NG("yt-remote-session-screen-id"),g.NG("yt-remote-session-video-id"));
q6();a=n6();g.sb(a,p6());Yya(a)},dza=function(){if(!s6){var a=g.WC();
a&&(s6=new g.KC(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},eza=function(){var a=window.document.createElement("a");
g.Xc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Za(a)},fza=function(a,b){var c=g.Bd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Yc(c,g.ae("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},gza=function(){var a=eza(),b=window.document.getElementById(a),c=b&&g.oF(b,"loaded");
c||b&&!c||(b=fza(a,function(){g.oF(b,"loaded")||(g.nF(b,"loaded","true"),g.fG(a),g.mE(g.Da(Pya,a),0))}))},hza=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?(0,window.parseInt)(a[1],10):0},t6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},iza=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},jza=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},x6=function(a){if(a>=kza.length)u6();
else{var b=kza[a],c="chrome-extension://"+b+lza;0<=v6.indexOf(b)?jza(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,w6(c,u6)):x6(a+1)}):w6(c,function(){x6(a+1)})}},w6=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},y6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},u6=function(){var a=iza();
a&&a(!1,"No cast extension found")},nza=function(){if(mza){var a=2,b=iza(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;w6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},oza=function(){if(y6("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){nza();a({command:"cast.sender.init"});return}}if(!window.chrome||y6("Edge"))u6();else if(nza(),y6("Android")&&y6("Chrome/")&&window.navigator.presentation){a="";var b=hza();55<=b?a="55":50<=b&&(a="50");w6("//www.gstatic.com/eureka/clank"+a+lza,u6)}else x6(0)},z6=function(a,b,c){g.L.call(this);
this.D=null!=c?(0,g.z)(a,c):a;this.tc=b;this.C=(0,g.z)(this.zH,this);this.g=!1;this.o=0;this.A=this.Aa=null;this.B=[]},A6=function(a,b){this.g=a;
this.o=b},B6=function(a,b,c,d,e){this.g=a;
this.A=c;this.G=d;this.F=e||1;this.C=45E3;this.B=new g.xm(this);this.o=new g.qg;this.o.setInterval(250)},qza=function(a,b,c){a.gj=1;
a.jh=d6(b.clone());a.Ai=c;a.D=!0;pza(a,null)},C6=function(a,b,c,d,e){a.gj=1;
a.jh=d6(b.clone());a.Ai=null;a.D=c;e&&(a.NB=!1);pza(a,d)},pza=function(a,b){a.zl=(0,g.F)();
D6(a);a.Ah=a.jh.clone();e6(a.Ah,"t",a.F);a.Hl=0;a.Nc=a.g.lq(a.g.Bl()?b:null);0<a.Qq&&(a.zo=new g.Gk((0,g.z)(a.WC,a,a.Nc),a.Qq));a.B.V(a.Nc,"readystatechange",a.DS);var c=a.Zh?g.ac(a.Zh):{};a.Ai?(a.hp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Nc.send(a.Ah,a.hp,a.Ai,c)):(a.hp="GET",a.NB&&!g.xd&&(c.Connection="close"),a.Nc.send(a.Ah,a.hp,null,c));a.g.nf(1)},tza=function(a,b,c){for(var d=!0;!a.Lh&&a.Hl<c.length;){var e=rza(a,c);
if(e==E6){4==b&&(a.ai=4,F6(),d=!1);break}else if(e==sza){a.ai=4;F6();d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.ai=1,F6(),d=!1);a.sf=a.sf&&d;d||(H6(a),I6(a))},rza=function(a,b){var c=a.Hl,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return sza;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.Hl=d+c;return e},vza=function(a,b){a.zl=(0,g.F)();
D6(a);var c=b?window.location.hostname:"";a.Ah=a.jh.clone();g.qm(a.Ah,"DOMAIN",c);g.qm(a.Ah,"t",a.F);try{a.tf=new window.ActiveXObject("htmlfile")}catch(n){H6(a);a.ai=7;F6();I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in J6)k=J6[l];else if(l in uza)k=J6[l]=uza[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
J6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Zc(g.vc("b/12014412"),d);a.tf.open();a.tf.write(g.Rc(c));a.tf.close();a.tf.parentWindow.m=(0,g.z)(a.HR,a);a.tf.parentWindow.d=(0,g.z)(a.gB,a,!0);a.tf.parentWindow.rpcClose=(0,g.z)(a.gB,a,!1);c=a.tf.createElement("DIV");a.tf.parentWindow.document.body.appendChild(c);d=g.Hc(a.Ah.toString());d=g.Oa(g.Ec(d));d=g.Zc(g.vc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Rc(d);a.g.nf(1)},D6=function(a){a.mu=
(0,g.F)()+a.C;
wza(a,a.C)},wza=function(a,b){if(null!=a.fk)throw Error("WatchDog timer not null");
a.fk=K6((0,g.z)(a.YR,a),b)},L6=function(a){a.fk&&(g.w.clearTimeout(a.fk),a.fk=null)},I6=function(a){a.g.ox()||a.Lh||a.g.qo(a)},H6=function(a){L6(a);
g.We(a.zo);a.zo=null;a.o.stop();g.Dm(a.B);if(a.Nc){var b=a.Nc;a.Nc=null;b.abort();b.dispose()}a.tf&&(a.tf=null)},G6=function(a,b){try{a.g.ZA(a,b),a.g.nf(4)}catch(c){}},yza=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;xza(a,b,function(e){e?c(!0):g.w.setTimeout(function(){yza(a,b,c,d,f)},f)})}},xza=function(a,b,c){var d=new window.Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},zza=function(a){this.g=a;
this.o=new A6},Aza=function(a){var b=N6(a.g,a.jk,"/mail/images/cleardot.gif");
d6(b);yza(b.toString(),5E3,(0,g.z)(a.HG,a),3,2E3);a.nf(1)},P6=function(a){var b=a.g.J;
if(null!=b)F6(),b?(F6(),O6(a.g,a,!1)):(F6(),O6(a.g,a,!0));else if(a.oe=new B6(a,0,void 0,void 0,void 0),a.oe.Zh=a.Nq,b=a.g,b=N6(b,b.Bl()?a.Kk:null,a.Pq),F6(),!g.vd||g.rc(10))e6(b,"TYPE","xmlhttp"),C6(a.oe,b,!1,a.Kk,!1);else{e6(b,"TYPE","html");var c=a.oe;a=!!a.Kk;c.gj=3;c.jh=d6(b.clone());vza(c,a)}},Q6=function(a,b,c,d){this.G=a||null;
this.g=1;this.o=[];this.B=[];this.C=new A6;this.I=b||null;this.J=null!=c?c:null;this.D=d||!1},Bza=function(a,b){this.g=a;
this.map=b;this.context=null},Cza=function(a){g.Ye.call(this,"statevent",a)},Dza=function(a,b){g.Ye.call(this,"timingevent",a);
this.size=b},Eza=function(a){g.Ye.call(this,"serverreachability",a)},Hza=function(a){Fza(a);
if(3==a.g){var b=a.ql++,c=a.hn.clone();g.qm(c,"SID",a.A);g.qm(c,"RID",b);g.qm(c,"TYPE","terminate");R6(a,c);b=new B6(a,0,a.A,b,void 0);b.gj=2;b.jh=d6(c.clone());(new window.Image).src=b.jh;b.zl=(0,g.F)();D6(b)}Gza(a)},Iza=function(a){a.eH(1,0);
a.hn=N6(a,null,a.Mq);S6(a)},Fza=function(a){a.Zg&&(a.Zg.abort(),a.Zg=null);
a.qc&&(a.qc.cancel(),a.qc=null);a.og&&(g.w.clearTimeout(a.og),a.og=null);T6(a);a.Od&&(a.Od.cancel(),a.Od=null);a.bh&&(g.w.clearTimeout(a.bh),a.bh=null)},Jza=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.o.push(new Bza(a.GN++,b));2!=a.g&&3!=a.g||S6(a)},S6=function(a){a.Od||a.bh||(a.bh=K6((0,g.z)(a.eB,a),0),a.zk=0)},Lza=function(a,b){if(1==a.g){if(!b){a.ql=Math.floor(1E5*Math.random());
var c=a.ql++,d=new B6(a,0,"",c,void 0);d.Zh=null;var e=U6(a),f=a.hn.clone();g.qm(f,"RID",c);a.G&&g.qm(f,"CVER",a.G);R6(a,f);qza(d,f,e);a.Od=d;a.g=2}}else 3==a.g&&(b?Kza(a,b):0==a.o.length||a.Od||Kza(a))},Kza=function(a,b){if(b)if(6<a.Nh){a.o=a.B.concat(a.o);
a.B.length=0;var c=a.ql-1;var d=U6(a)}else c=b.G,d=b.Ai;else c=a.ql++,d=U6(a);var e=a.hn.clone();g.qm(e,"SID",a.A);g.qm(e,"RID",c);g.qm(e,"AID",a.uj);R6(a,e);c=new B6(a,0,a.A,c,a.zk+1);c.Zh=null;c.setTimeout(Math.round(1E4)+Math.round(1E4*Math.random()));a.Od=c;qza(c,e,d)},R6=function(a,b){if(a.pd){var c=a.pd.Qw(a);
c&&g.Kb(c,function(a,c){g.qm(b,c,a)})}},U6=function(a){var b=Math.min(a.o.length,1E3),c=["count="+b];
if(6<a.Nh&&0<b){var d=a.o[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.o[e].g,k=a.o[e].map;f=6>=a.Nh?e:f-d;try{g.Kb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.B=a.B.concat(a.o.splice(0,b));
return c.join("&")},Mza=function(a){a.qc||a.og||(a.F=1,a.og=K6((0,g.z)(a.dB,a),0),a.Qi=0)},V6=function(a){if(a.qc||a.og||3<=a.Qi)return!1;
a.F++;a.og=K6((0,g.z)(a.dB,a),Nza(a,a.Qi));a.Qi++;return!0},O6=function(a,b,c){a.gp=c;
a.af=b.ug;a.D||Iza(a)},T6=function(a){null!=a.Ph&&(g.w.clearTimeout(a.Ph),a.Ph=null)},Nza=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},W6=function(a,b){if(2==b||9==b){var c=null;
a.pd&&(c=null);var d=(0,g.z)(a.uT,a);c||(c=new g.hm("//www.google.com/images/cleardot.gif"),d6(c));xza(c.toString(),1E4,d)}else F6();Oza(a,b)},Oza=function(a,b){a.g=0;
a.pd&&a.pd.Sv(a,b);Gza(a);Fza(a)},Gza=function(a){a.g=0;
a.af=-1;if(a.pd)if(0==a.B.length&&0==a.o.length)a.pd.Zp(a);else{var b=g.vb(a.B),c=g.vb(a.o);a.B.length=0;a.o.length=0;a.pd.Zp(a,b,c)}},N6=function(a,b,c){var d=g.rm(c);
if(""!=d.o)b&&g.jm(d,b+"."+d.o),g.km(d,d.C);else{var e=window.location;d=Nya(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.wk&&g.Kb(a.wk,function(a,b){g.qm(d,b,a)});
g.qm(d,"VER",a.Nh);R6(a,d);return d},K6=function(a,b){if(!g.za(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},F6=function(){X6.dispatchEvent(new Cza(X6))},Pza=function(){},Qza=function(a,b){this.action=a;
this.params=b||{}},Z6=function(a,b){g.L.call(this);
this.g=new g.Ot(this.A,0,this);g.M(this,this.g);this.o=this.tc=0;if(g.za(a))b&&(a=(0,g.z)(a,b));else if(a&&g.za(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a;Y6(this)},Y6=function(a){a.g.stop();
a.tc=5E3+2E4*Math.random()},$6=function(a,b,c){this.L=a;
this.D=b;this.A=new g.JC;this.o=new Z6(this.XT,this);this.g=this.Za=null;this.J=!1;this.C=null;this.I="";this.G=this.B=0;this.F=[];this.N=c||!1},Rza=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.gp,sessionId:a.g.A,arrayId:a.g.uj}},Sza=function(a,b){a.G=b||0;
a.o.stop();a.g&&(3==a.g.g&&Lza(a.g),Hza(a.g));a.G=0},a7=function(a){return!!a.g&&3==a.g.g},Tza=function(a,b){(a.D.loungeIdToken=b)||a.o.stop()},b7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Gg(a)||"";b&&(this.port=":"+b);this.domain=g.Fg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ya(a,"10.0")&&(this.o=!1))},c7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.o)c="https://"+a.domain+a.port+a.g;return g.Pg(c+b,{})},d7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Fb:g.Da(a.B,d,!0),onError:g.Da(a.A,e),sd:g.Da(a.C,e)};c&&(a.Ob=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.CE(b,a)},Xza=function(){var a=Uza;
Vza();e7.push(a);Wza(e7)},f7=function(a,b){Vza();
var c=e7,d=Yza(a,String(b));g.ob(c)?Zza(d):(Wza(c),(0,g.G)(c,function(a){a(d)}))},Vza=function(){e7||(e7=g.x("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",e7,void 0))},Zza=function(a){var b=(g7+1)%50;
g7=b;h7[b]=a;i7||(i7=49==b)},Wza=function(a){var b=h7;
if(b[0]){var c=g7,d=i7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.G)(a,function(a){a(e)})}while(d!=c);
h7=Array(50);g7=-1;i7=!1}},Yza=function(a,b){var c=((0,g.F)()-$za)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},j7=function(a){g.QF.call(this);
this.F=a;this.g=[]},aAa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},bAa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Jd)(a.g,function(a){return!!l6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=aAa(a,b[d])||c;return c},cAa=function(a,b){var c=a.g.length;
a.g=(0,g.Jd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},k7=function(a,b,c,d){g.QF.call(this);
this.D=a;this.C=b;this.A=c;this.B=d;this.o=0;this.g=null;this.Aa=window.NaN},m7=function(a){j7.call(this,"LocalScreenService");
this.A=a;this.o=window.NaN;l7(this);this.info("Initializing with "+j6(this.g))},dAa=function(a){if(a.g.length){var b=(0,g.H)(a.g,function(a){return a.id}),c=c7(a.A,"/pairing/get_lounge_token_batch");
d7(a.A,c,{screen_ids:b.join(",")},(0,g.z)(a.LH,a),(0,g.z)(a.KH,a))}},l7=function(a){var b=Vya($ya());
b=(0,g.Jd)(b,function(a){return!a.uuid});
return bAa(a,b)},n7=function(a,b){bza((0,g.H)(a.g,Tya));
b&&aza()},p7=function(a,b){g.QF.call(this);
this.D=b;var c=g.MG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.D(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.kb(c,l)}this.g=d;this.C=a;this.A=this.B=window.NaN;this.o=null;o7("Initialized with "+g.xg(this.g))},eAa=function(a,b,c){var d=c7(a.C,"/pairing/get_screen_availability");
d7(a.C,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},q7=function(a,b){a:if(g.Pb(b)!=g.Pb(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(o7("Updated online screens: "+g.xg(a.g)),a.g=b,a.U("screenChange"));fAa(a)},r7=function(a){(0,window.isNaN)(a.A)||g.oE(a.A);
a.A=g.mE((0,g.z)(a.zt,a),0<a.B&&a.B<(0,g.F)()?2E4:1E4)},o7=function(a){f7("OnlineScreenService",a)},gAa=function(a){var b={};
(0,g.G)(a.D(),function(a){a.token?b[a.token]=a.id:this.ac("Requesting availability of screen w/o lounge token.")});
return b},fAa=function(a){a=g.Sb(g.Mb(a.g,function(a){return a}));
g.Eb(a);a.length?g.LG("yt-remote-online-screen-ids",a.join(","),60):g.NG("yt-remote-online-screen-ids")},s7=function(a){j7.call(this,"ScreenService");
this.D=a;this.o=this.A=null;this.B=[];this.C={};hAa(this)},jAa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var k=a.fe();if(k=(c?m6(k,c):null)||m6(k,b)){k.uuid=b;var l=t7(a,k);eAa(a.o,l,function(a){e(a?l:null)})}else c?iAa(a,c,(0,g.z)(function(a){var f=t7(this,new g6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));eAa(this.o,f,function(a){e(a?f:null)})},a),f):e(null)},kAa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},iAa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Ob:{screen_ids:b},method:"POST",context:a,Fb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.CE(c7(a.D,"/pairing/get_lounge_token_batch"),e)},lAa=function(a){a.g=a.A.fe();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.g))},hAa=function(a){u7(a);
a.A=new m7(a.D);a.A.subscribe("screenChange",(0,g.z)(a.XH,a));lAa(a);a.B=Vya(g.MG("yt-remote-automatic-screen-cache")||[]);u7(a);a.info("Initializing automatic screens: "+j6(a.B));a.o=new p7(a.D,(0,g.z)(a.fe,a,!0));a.o.subscribe("screenChange",(0,g.z)(function(){this.U("onlineScreenChange")},a))},t7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),g.LG("yt-remote-automatic-screen-cache",(0,g.H)(a.B,Tya)));u7(a);a.C[b.uuid]=b.id;g.LG("yt-remote-device-id-map",a.C,31536E3);return b},u7=function(a){a.C=g.MG("yt-remote-device-id-map")||{}},v7=function(a,b,c){g.QF.call(this);
this.N=c;this.I=a;this.o=b;this.A=null},w7=function(a,b){f7(a.N,b)},x7=function(a,b){v7.call(this,a,b,"CastSession");
this.g=null;this.B=0;this.D=(0,g.z)(this.eU,this);this.C=(0,g.z)(this.iS,this);this.B=g.mE((0,g.z)(function(){mAa(this,null)},this),12E4)},nAa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.xg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){w7(this,"Failed to send message: getMdxSessionStatus.")},a)):w7(a,"Sending yt message without session: "+g.xg(b))},mAa=function(a,b){g.oE(a.B);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.A||a.A.id!=b){var c=(0,g.z)(a.ro,a),d=(0,g.z)(a.ke,a);a.fx(b,c,d,5)}}else a.ke(Error("Waiting for session status timed out."))},y7=function(a,b,c){v7.call(this,a,b,"DialSession");
this.B=this.G=null;this.J="";this.O=c;this.C=null;this.F=g.y;this.D=window.NaN;this.L=(0,g.z)(this.hU,this);this.g=g.y},oAa=function(a){a.g=a.I.dD(a.J,a.o.label,a.o.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.ro(a)},a),(0,g.z)(function(a){this.g=g.y;
this.ke(a)},a))},pAa=function(a){var b={};
b.pairingCode=a.J;b.theme=a.O;if(a.C){var c=a.C.currentTime||0;b.v=a.C.videoId;b.t=c}dza()&&(b.env_useStageMdx=1);return g.Ng(b)},z7=function(a,b){v7.call(this,a,b,"ManualSession");
this.g=g.mE((0,g.z)(this.vj,this,null),150)},A7=function(a,b,c,d){g.QF.call(this);
this.o=a;this.F=b||"233637DE";this.D=c||"cl";this.G=d||!1;this.g=null;this.C=!1;this.A=[];this.B=(0,g.z)(this.OQ,this)},qAa=function(a,b){return b?g.fb(a.A,function(a){return h6(b,a.label)},a):null},B7=function(a){f7("Controller",a)},Uza=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},C7=function(a){return a.C||!!a.A.length||!!a.g},D7=function(a,b,c){b!=a.g&&(g.We(a.g),(a.g=b)?(c?a.U("yt-remote-cast2-receiver-resumed",b.o):a.U("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.z)(a.bB,a,b)),b.A?a.U("yt-remote-cast2-session-change",b.A):c&&a.g.vj(null)):a.U("yt-remote-cast2-session-change",null))},rAa=function(a){var b=a.o.cD(),c=a.g&&a.g.o;
a=(0,g.H)(b,function(a){c&&h6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=qAa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},wAa=function(a,b,c,d,e,f,k){sAa()?tAa(b,e,f,k)&&(F7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?uAa(a,c):(window.__onGCastApiAvailable=function(b,d){b?uAa(a,c):(G7("Failed to load cast API: "+d),H7(!1),F7(!1),g.NG("yt-remote-cast-available"),g.NG("yt-remote-cast-receiver"),vAa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):gza():oza())):E7("Cannot initialize because not running Chrome")},vAa=function(){E7("dispose");
var a=I7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);xAa(!1);g.dG(J7);J7.length=0},K7=function(){return!!g.MG("yt-remote-cast-installed")},yAa=function(){var a=g.MG("yt-remote-cast-receiver");
return a?a.friendlyName:null},zAa=function(){E7("clearCurrentReceiver");
g.NG("yt-remote-cast-receiver")},AAa=function(){return K7()?I7()?I7().getCastSession():(G7("getCastSelector: Cast is not initialized."),null):(G7("getCastSelector: Cast API is not installed!"),null)},M7=function(){K7()?I7()?L7()?(E7("Requesting cast selector."),I7().requestSession()):(E7("Wait for cast API to be ready to request the session."),J7.push(g.cG("yt-remote-cast2-api-ready",M7))):G7("requestCastSelector: Cast is not initialized."):G7("requestCastSelector: Cast API is not installed!")},N7=
function(a,b){L7()?I7().setConnectedScreenStatus(a,b):G7("setConnectedScreenStatus called before ready.")},sAa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.xJ||a},BAa=function(a,b){I7().init(a,b)},tAa=function(a,b,c,d){var e=!1;
I7()||(a=new A7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.LG("yt-remote-cast-available",a);g.gG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){E7("onReceiverSelected: "+a.friendlyName);
g.LG("yt-remote-cast-receiver",a);g.gG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){E7("onReceiverResumed: "+a.friendlyName);
g.LG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){E7("onSessionChange: "+i6(a));
a||g.NG("yt-remote-cast-receiver");g.gG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
E7("cloudview.createSingleton_: "+e);return e},I7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},uAa=function(a,b){H7(!0);
F7(!1);BAa(a,function(a){a?(xAa(!0),g.fG("yt-remote-cast2-api-ready")):(G7("Failed to initialize cast API."),H7(!1),g.NG("yt-remote-cast-available"),g.NG("yt-remote-cast-receiver"),vAa());b(a)})},E7=function(a){f7("cloudview",a)},G7=function(a){f7("cloudview",a)},H7=function(a){E7("setCastInstalled_ "+a);
g.LG("yt-remote-cast-installed",a)},L7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},xAa=function(a){E7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},F7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},O7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.If=!1;this.J=this.I=this.A=this.C=0;this.B=window.NaN;this.D=!1;this.reset(a)},P7=function(a){a.audioTrackId=null;
a.o=null;a.g=-1;a.If=!1;a.hasNext=!1;a.G=0;a.F=(0,g.F)();a.C=0;a.A=0;a.I=0;a.J=0;a.B=window.NaN;a.D=!1},Q7=function(a){return a.jb()?((0,g.F)()-a.F)/1E3:0},R7=function(a,b){a.G=b;
a.F=(0,g.F)()},S7=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},T7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&P7(a)},U7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.o);b.hasPrevious=a.If;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.I;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},W7=function(a,b){g.QF.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.$B;this.A=this.o=null;this.I=(0,g.z)(this.rO,this);this.F=(0,g.z)(this.sl,this);this.G=(0,g.z)(this.qO,this);this.J=(0,g.z)(this.EO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.tu,this),CAa(this))):c=3;0!=c&&(b?this.tu(c):g.mE((0,g.z)(function(){this.tu(c)},this),0));
var d=AAa();d&&V7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},X7=function(a){return new O7(a.B.getPlayerContextData())},CAa=function(a){(0,g.G)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Da(this.KQ,a),this))},a)},DAa=function(a){(0,g.G)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},Y7=function(a,b){50>a.C.Jc()&&g.bC(a.C,b)},$7=function(a,b,c){var d=X7(a);
R7(d,c);-1E3!=d.g&&(d.g=b);Z7(a,d)},a8=function(a,b,c){a.B.sendMessage(b,c)},Z7=function(a,b){DAa(a);
a.B.setPlayerContextData(U7(b));CAa(a)},V7=function(a,b){a.A&&(a.A.removeUpdateListener(a.I),a.A.removeMediaListener(a.F),a.sl(null));
a.A=b;a.A&&(b8("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.I),a.A.addMediaListener(a.F),a.A.media.length&&a.sl(a.A.media[0]))},EAa=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=X7(a);b.contentId!=d.videoId&&b8("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;R7(d,a.o.getEstimatedTime());Z7(a,d)}else b8("No cast media video. Ignoring state update.")},b8=function(a){f7("CP",a)},c8=function(a,b,c){return(0,g.z)(function(a){this.ac("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.ac("Retrying "+b+" using MDx browser channel."),a8(this,b,c))},a)},d8=function(a,b,c){g.QF.call(this);
this.C=window.NaN;this.O=!1;this.J=this.I=this.L=this.N=window.NaN;this.T=[];this.B=this.F=this.A=this.bb=this.g=null;this.oa=a;this.T.push(g.BF(window,"beforeunload",(0,g.z)(this.CH,this)));this.o=[];this.bb=new O7;this.aa=b.id;this.g=FAa(this,c);this.g.subscribe("handlerOpened",this.vO,this);this.g.subscribe("handlerClosed",this.sO,this);this.g.subscribe("handlerError",this.tO,this);this.g.subscribe("handlerMessage",this.uO,this);Tza(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.bb.videoId;g.RG()&&g.LG("yt-remote-session-video-id",a)},this)},e8=function(a){f7("conn",a)},FAa=function(a,b){return new $6(c7(a.oa,"/bc"),b)},f8=function(a,b){a.U("proxyStateChange",b)},GAa=function(a){a.C=g.mE((0,g.z)(function(){e8("Connecting timeout");
this.D(1)},a),2E4)},g8=function(a){g.oE(a.C);
a.C=window.NaN},h8=function(a){g.oE(a.N);
a.N=window.NaN},HAa=function(a){i8(a);
a.L=g.mE((0,g.z)(function(){j8(this,"getNowPlaying")},a),2E4)},i8=function(a){g.oE(a.L);
a.L=window.NaN},JAa=function(a,b){b&&(g8(a),h8(a));
b==(a7(a.g)&&(0,window.isNaN)(a.C))?b&&(f8(a,1),j8(a,"getSubtitlesTrack")):b?(a.Y()&&a.bb.reset(),f8(a,1),j8(a,"getNowPlaying"),IAa(a)):a.D(1)},KAa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.bb.videoId&&(g.Yb(b.params)?a.bb.o=null:a.bb.o=b.params,a.U("remotePlayerChange"))},LAa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.bb.listId=b.params.listId||a.bb.listId;T7(a.bb,c,d);a.U("remoteQueueChange")},NAa=function(a,b){b.params=b.params||{};
LAa(a,b);MAa(a,b);a.U("autoplayDismissed")},MAa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
R7(a.bb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.bb.g&&(c=-1E3);a.bb.g=c;c=Number(b.params.loadedTime);a.bb.J=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.bb.I=(0,window.isNaN)(c)?0:c;c=a.bb;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=(0,window.isNaN)(d)?!1:!0;c=a.bb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=(0,window.isNaN)(d)?0:d;c.A=(0,window.isNaN)(e)?0:e;1==a.bb.g?HAa(a):i8(a);
a.U("remotePlayerChange")},OAa=function(a,b){if(-1E3!=a.bb.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.bb.g=c;c=(0,window.parseInt)(b.params.currentTime,10);R7(a.bb,(0,window.isNaN)(c)?0:c);a.U("remotePlayerChange")}},PAa=function(a,b){var c="true"==b.params.muted;
a.bb.volume=(0,window.parseInt)(b.params.volume,10);a.bb.muted=c;a.U("remotePlayerChange")},QAa=function(a,b){a.F=b.params.videoId;
a.U("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},RAa=function(a,b){var c="true"==b.params.hasNext;
a.bb.If="true"==b.params.hasPrevious;a.bb.hasNext=c;a.U("previousNextChange")},IAa=function(a){g.oE(a.J);
a.J=g.mE((0,g.z)(a.D,a,1),864E5)},j8=function(a,b,c){c?e8("Sending: action="+b+", params="+g.xg(c)):e8("Sending: action="+b);
a.g.sendMessage(b,c)},k8=function(a){j7.call(this,"ScreenServiceProxy");
this.bd=a;this.o=[];this.o.push(this.bd.$_s("screenChange",(0,g.z)(this.cU,this)));this.o.push(this.bd.$_s("onlineScreenChange",(0,g.z)(this.qQ,this)))},WAa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.FD("MDX_CONFIG")||b;g.JG&&Mya();q6();l8||(l8=new b7(b?b.loungeApiHost:void 0),dza()&&(l8.g="/api/loungedev"));m8||(m8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",m8,void 0));SAa();var c=n8();if(!c){var d=new s7(l8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=n8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);wAa(a,d,function(a){a?o8()&&N7(o8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.gG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),p8("Initializing: "+g.xg(b)),q8.push(g.cG("yt-remote-cast2-availability-change",function(){g.gG("yt-remote-receiver-availability-change")})),q8.push(g.cG("yt-remote-cast2-receiver-selected",function(){r8(null);
g.gG("yt-remote-auto-connect","cast-selector-receiver")})),q8.push(g.cG("yt-remote-cast2-receiver-resumed",function(){g.gG("yt-remote-receiver-resumed","cast-selector-receiver")})),q8.push(g.cG("yt-remote-cast2-session-change",TAa)),q8.push(g.cG("yt-remote-connection-change",function(a){a?N7(o8(),"YouTube TV"):s8()||(N7(null,null),zAa())})),a=t8(),b.isAuto&&(a.id+="#dial"),g.UE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),p8(" -- with channel params: "+
g.xg(a)),UAa(a),c.start(),o8()||VAa())},YAa=function(){var a=XAa();
K7()&&g.MG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},XAa=function(){var a=n8().bd.$_gos();
var b=u8();b&&v8()&&(l6(a,b)||a.push(b));return Wya(a)},w8=function(){var a=ZAa();
!a&&K7()&&yAa()&&(a={key:"cast-selector-receiver",name:yAa()});return a},ZAa=function(){var a=XAa(),b=u8();
b||(b=s8());return g.fb(a,function(a){return b&&h6(b,a.key)?!0:!1})},u8=function(){var a=o8();
if(!a)return null;var b=n8().fe();return m6(b,a)},TAa=function(a){p8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=u8();b&&b.id==a.id?N7(b.id,"YouTube TV"):(b&&x8(),y8(a,1))}else v8()&&x8()},x8=function(){L7()?I7().stopSession():G7("stopSession called before API ready.");
var a=v8();a&&(a.disconnect(1),z8(null))},A8=function(){var a=v8();
return!!a&&3!=a.getProxyState()},p8=function(a){f7("remote",a)},n8=function(){if(!B8){var a=g.x("yt.mdx.remote.screenService_");
B8=a?new k8(a):null}return B8},o8=function(){return g.x("yt.mdx.remote.currentScreenId_")},$Aa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},aBa=function(){return g.x("yt.mdx.remote.connectData_")},r8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},v8=function(){return g.x("yt.mdx.remote.connection_")},z8=function(a){var b=v8();
r8(null);a||$Aa("");g.ua("yt.mdx.remote.connection_",a,void 0);m8&&((0,g.G)(m8,function(b){b(a)}),m8.length=0);
b&&!a?g.gG("yt-remote-connection-change",!1):!b&&a&&g.gG("yt-remote-connection-change",!0)},s8=function(){var a=g.RG();
if(!a)return null;var b=n8().fe();return m6(b,a)},y8=function(a,b){u8()&&u8();
$Aa(a.id);var c=new d8(l8,a,t8());c.connect(b,aBa());c.subscribe("beforeDisconnect",function(a){g.gG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){v8()&&z8(null)});
z8(c)},VAa=function(){var a=s8();
a?(p8("Resume connection to: "+i6(a)),y8(a,0)):(r6(),zAa(),p8("Skipping connecting because no session screen found."))},SAa=function(){var a=t8();
if(g.Yb(a)){a=p6();var b=g.MG("yt-remote-session-name")||"",c=g.MG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},t8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},UAa=function(a){a?(g.LG("yt-remote-session-app",a.app),g.LG("yt-remote-session-name",a.name)):(g.NG("yt-remote-session-app"),g.NG("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},C8=function(a,b,c){g.L.call(this);
this.F=a;this.R=b;this.o=new g.NF(this);g.M(this,this.o);this.o.P(b,"onCaptionsTrackListChanged",this.JP);this.o.P(b,"captionschanged",this.pO);this.o.P(b,"captionssettingschanged",this.sC);this.o.P(b,"videoplayerreset",this.so);this.o.P(b,"mdxautoplaycancel",this.GG);this.O=this.o.P(b,"onVolumeChange",this.LA);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.YA,this);c.subscribe("remotePlayerChange",this.ul,this);c.subscribe("remoteQueueChange",this.so,this);c.subscribe("autoplayUpNext",this.xA,
this);c.subscribe("previousNextChange",this.VA,this);c.subscribe("nowAutoplaying",this.NA,this);c.subscribe("autoplayDismissed",this.wA,this);this.suggestion=null;this.G=new g.yO(64);this.A=new g.Ot(this.nC,500,this);g.M(this,this.A);this.B=new g.Ot(this.oC,1E3,this);g.M(this,this.B);this.J=new z6(this.CT,0,this);g.M(this,this.J);this.C={};this.L=new g.Ot(this.QC,1E3,this);g.M(this,this.L);this.I=new g.Gk(this.aL,1E3,this);g.M(this,this.I);this.N=g.y;this.sC();this.so();this.ul()},D8=function(a,b){var c=
a.F,d=a.R.ga().lengthSeconds;
c.I=b||0;c.g.U("progresssync",b,d)},bBa=function(a){D8(a,0);
a.A.stop();P8(a,new g.yO(64))},b9=function(a,b){if(a9(a)&&!a.D){var c=null;
b&&(c={style:a.R.oi()},g.dc(c,b));a.g.eC(a.R.ga(1).videoId,c);a.C=X7(a.g).o}},j9=function(a,b){var c=a.R.Sf();
if(c){var d=c.ce();var e=c.listId.toString()}var f=a.R.ga(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.qj;var m=X7(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};T7(m,k,l);g.t(b)&&(R7(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);a8(c,"setPlaylist",q);e||Z7(c,m);P8(a,new g.yO(1))},cBa=function(a,b){if(b){var c=a.R.yc("captions","tracklist",{ey:1});
c&&c.length?(a.R.Gd("captions","track",b),a.D=!1):(a.R.il("captions"),a.D=!0)}else a.R.Gd("captions","track",{})},a9=function(a){return X7(a.g).videoId==a.R.ga(1).videoId},P8=function(a,b){a.B.stop();
var c=a.G;if(!g.EO(c,b)){var d=g.W(b,2);d!=g.W(a.G,2)&&g.EU(a.R,d);a.G=b;dBa(a.F,c,b)}},m9=function(a){g.Y.call(this,{H:"div",
M:"ytp-remote",K:[{H:"div",M:"ytp-remote-display-status",K:[{H:"div",M:"ytp-remote-display-status-icon",K:[g.KD()]},{H:"div",M:"ytp-remote-display-status-text",K:["{{statustext}}"]}]}]});this.o=new g.FV(this,250);g.M(this,this.o);this.A=a;this.P(a,"presentingplayerstatechange",this.B);eBa(this,g.BU(a))},eBa=function(a,b){if(3==a.A.Ra()){var c={RECEIVER_NAME:a.A.yc("remote","currentReceiver").name};
c=g.W(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.jb()||g.W(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},n9=function(a,b){g.e_.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.R=a;this.F={};this.P(a,"onMdxReceiversChange",this.I);this.P(a,"presentingplayerstatechange",this.I);this.I()},o9=function(a){g.xV.call(this,a);
this.A={key:k6(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.yO(64);this.I=0;if(!g.eM(g.X(this.g))){a=this.g;var b=g.uU(a).G;b&&(b=b.A&&b.A.g)&&(b=new n9(a,b),g.M(this,b));b=new m9(a);g.M(this,b);g.VU(a,b.element,4)}},dBa=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.YO(c,b))},p9=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)x8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ga(1),e=d.videoId;if(c||e){var f=a.g.Sf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.gc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.qj,index:Math.max(a.g.oz(),0),currentTime:0==f?void 0:f}}else c=null;p8("Connecting to: "+g.xg(b));"cast-selector-receiver"==b.key?(r8(c||null),L7()?I7().setLaunchParams(c||null):G7("setLaunchParams called before ready.")):!c&&
A8()&&o8()==b.key?g.gG("yt-remote-connection-change",!0):(x8(),r8(c||null),c=n8().fe(),(c=m6(c,b.key))&&y8(c,1))}},uza={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},J6={"'":"\\'"},fBa={},Sya={JV:"atp",f0:"ska",w_:"que",JZ:"mus",b0:"sus"};
f6.prototype.Qm=function(){var a=new f6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.A=this.A;a.o=this.o;a.g=this.g;return a};
var s6,o6="",lza=t6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",mza=t6("loadCastFramework")||t6("loadCastApplicationFramework"),v6=["boadgeojelhgndaghljhdicfkmllpafd","dliochdbjfkdbacpmhlcpmleaejidimm","enhhojjnijigcajfphajepfemndkmdlo","fmfcbgogabcbclcofgocippekhfcmgfj"],gBa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","fjhoaacokmgbjemoflkofnenfaiekifl"],kza=50<=hza()?gBa.concat(v6):v6.concat(gBa);g.A(z6,g.L);g.h=z6.prototype;g.h.yH=function(a){this.B=arguments;this.g=!1;this.Aa?this.A=(0,g.F)()+this.tc:this.Aa=g.rg(this.C,this.tc)};
g.h.stop=function(){this.Aa&&(g.sg(this.Aa),this.Aa=null);this.A=null;this.g=!1;this.B=[]};
g.h.pause=function(){++this.o};
g.h.resume=function(){this.o&&(--this.o,!this.o&&this.g&&(this.g=!1,this.D.apply(null,this.B)))};
g.h.X=function(){this.stop();z6.Z.X.call(this)};
g.h.zH=function(){this.A?(this.Aa=g.rg(this.C,this.A-(0,g.F)()),this.A=null):(this.Aa=null,this.o?this.g=!0:(this.g=!1,this.D.apply(null,this.B)))};A6.prototype.stringify=function(a){return g.w.JSON.stringify(a,this.g)};
A6.prototype.parse=function(a){return g.w.JSON.parse(a,this.o)};g.h=B6.prototype;g.h.Zh=null;g.h.sf=!1;g.h.fk=null;g.h.mu=null;g.h.zl=null;g.h.gj=null;g.h.jh=null;g.h.Ah=null;g.h.Ai=null;g.h.Nc=null;g.h.Hl=0;g.h.tf=null;g.h.hp=null;g.h.ai=null;g.h.Lk=-1;g.h.NB=!0;g.h.Lh=!1;g.h.Qq=0;g.h.zo=null;var sza={},E6={};g.h=B6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.DS=function(a){a=a.target;var b=this.zo;b&&3==g.hx(a)?b.ej():this.WC(a)};
g.h.WC=function(a){try{if(a==this.Nc)a:{var b=g.hx(this.Nc),c=this.Nc.o,d=this.Nc.getStatus();if(g.vd&&!g.rc(10)||g.xd&&!g.qc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.$e&&!g.lx(this.Nc))break a;this.Lh||4!=b||7==c||(8==c||0>=d?this.g.nf(3):this.g.nf(2));L6(this);var e=this.Nc.getStatus();this.Lk=e;var f=g.lx(this.Nc);(this.sf=200==e)?(4==b&&H6(this),this.D?(tza(this,b,f),g.$e&&this.sf&&3==b&&(this.B.V(this.o,"tick",this.uS),this.o.start())):G6(this,f),this.sf&&!this.Lh&&(4==b?this.g.qo(this):
(this.sf=!1,D6(this)))):(this.ai=400==e&&0<f.indexOf("Unknown SID")?3:0,F6(),H6(this),I6(this))}}catch(k){this.Nc&&g.lx(this.Nc)}finally{}};
g.h.uS=function(){var a=g.hx(this.Nc),b=g.lx(this.Nc);this.Hl<b.length&&(L6(this),tza(this,a,b),this.sf&&4!=a&&D6(this))};
g.h.HR=function(a){K6((0,g.z)(this.GR,this,a),0)};
g.h.GR=function(a){this.Lh||(L6(this),G6(this,a),D6(this))};
g.h.gB=function(a){K6((0,g.z)(this.FR,this,a),0)};
g.h.FR=function(a){this.Lh||(H6(this),this.sf=a,this.g.qo(this),this.g.nf(4))};
g.h.cancel=function(){this.Lh=!0;H6(this)};
g.h.YR=function(){this.fk=null;var a=(0,g.F)();0<=a-this.mu?(2!=this.gj&&this.g.nf(3),H6(this),this.ai=2,F6(),I6(this)):wza(this,this.mu-a)};g.h=zza.prototype;g.h.Nq=null;g.h.oe=null;g.h.Bo=!1;g.h.qx=null;g.h.cn=null;g.h.Oq=null;g.h.Pq=null;g.h.Ie=null;g.h.ug=-1;g.h.Kk=null;g.h.jk=null;g.h.connect=function(a){this.Pq=a;a=N6(this.g,null,this.Pq);F6();this.qx=(0,g.F)();var b=this.g.I;null!=b?(this.Kk=b[0],(this.jk=b[1])?(this.Ie=1,Aza(this)):(this.Ie=2,P6(this))):(e6(a,"MODE","init"),this.oe=new B6(this,0,void 0,void 0,void 0),this.oe.Zh=this.Nq,C6(this.oe,a,!1,null,!0),this.Ie=0)};
g.h.HG=function(a){if(a)this.Ie=2,P6(this);else{F6();var b=this.g;b.af=b.Zg.ug;W6(b,9)}a&&this.nf(2)};
g.h.lq=function(a){return this.g.lq(a)};
g.h.abort=function(){this.oe&&(this.oe.cancel(),this.oe=null);this.ug=-1};
g.h.ox=function(){return!1};
g.h.ZA=function(a,b){this.ug=a.Lk;if(0==this.Ie)if(b){try{var c=this.o.parse(b)}catch(d){c=this.g;c.af=this.ug;W6(c,2);return}this.Kk=c[0];this.jk=c[1]}else c=this.g,c.af=this.ug,W6(c,2);else if(2==this.Ie)if(this.Bo)F6(),this.Oq=(0,g.F)();else if("11111"==b){if(F6(),this.Bo=!0,this.cn=(0,g.F)(),c=this.cn-this.qx,!g.vd||g.rc(10)||500>c)this.ug=200,this.oe.cancel(),F6(),O6(this.g,this,!0)}else F6(),this.cn=this.Oq=(0,g.F)(),this.Bo=!1};
g.h.qo=function(){this.ug=this.oe.Lk;if(this.oe.sf)0==this.Ie?this.jk?(this.Ie=1,Aza(this)):(this.Ie=2,P6(this)):2==this.Ie&&((!g.vd||g.rc(10)?!this.Bo:200>this.Oq-this.cn)?(F6(),O6(this.g,this,!1)):(F6(),O6(this.g,this,!0)));else{0==this.Ie?F6():2==this.Ie&&F6();var a=this.g;a.af=this.ug;W6(a,2)}};
g.h.Bl=function(){return this.g.Bl()};
g.h.isActive=function(){return this.g.isActive()};
g.h.nf=function(a){this.g.nf(a)};g.h=Q6.prototype;g.h.wk=null;g.h.Od=null;g.h.qc=null;g.h.Mq=null;g.h.hn=null;g.h.Hv=null;g.h.zn=null;g.h.ql=0;g.h.GN=0;g.h.pd=null;g.h.bh=null;g.h.og=null;g.h.Ph=null;g.h.Zg=null;g.h.gp=null;g.h.uj=-1;g.h.oy=-1;g.h.af=-1;g.h.zk=0;g.h.Qi=0;g.h.Nh=8;var X6=new g.zf;g.A(Cza,g.Ye);g.A(Dza,g.Ye);g.A(Eza,g.Ye);g.h=Q6.prototype;g.h.connect=function(a,b,c,d,e){F6();this.Mq=b;this.wk=c||{};d&&g.t(e)&&(this.wk.OSID=d,this.wk.OAID=e);this.D?(K6((0,g.z)(this.gw,this,a),100),Iza(this)):this.gw(a)};
g.h.gw=function(a){this.Zg=new zza(this);this.Zg.Nq=null;this.Zg.o=this.C;this.Zg.connect(a)};
g.h.ox=function(){return 0==this.g};
g.h.eB=function(a){this.bh=null;Lza(this,a)};
g.h.dB=function(){this.og=null;this.qc=new B6(this,0,this.A,"rpc",this.F);this.qc.Zh=null;this.qc.Qq=0;var a=this.Hv.clone();g.qm(a,"RID","rpc");g.qm(a,"SID",this.A);g.qm(a,"CI",this.gp?"0":"1");g.qm(a,"AID",this.uj);R6(this,a);if(!g.vd||g.rc(10))g.qm(a,"TYPE","xmlhttp"),C6(this.qc,a,!0,this.zn,!1);else{g.qm(a,"TYPE","html");var b=this.qc,c=!!this.zn;b.gj=3;b.jh=d6(a.clone());vza(b,c)}};
g.h.ZA=function(a,b){if(0!=this.g&&(this.qc==a||this.Od==a))if(this.af=a.Lk,this.Od==a&&3==this.g)if(7<this.Nh){try{var c=this.C.parse(b)}catch(f){c=null}if(g.xa(c)&&3==c.length)if(0==c[0])a:{if(!this.og){if(this.qc)if(this.qc.zl+3E3<this.Od.zl)T6(this),this.qc.cancel(),this.qc=null;else break a;V6(this);F6()}}else this.oy=c[1],0<this.oy-this.uj&&37500>c[2]&&this.gp&&0==this.Qi&&!this.Ph&&(this.Ph=K6((0,g.z)(this.kO,this),6E3));else W6(this,11)}else b!=fBa.LW.g&&W6(this,11);else if(this.qc==a&&T6(this),
!g.C(b)){c=this.C.parse(b);g.xa(c);for(var d=0;d<c.length;d++){var e=c[d];this.uj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.A=e[1],this.zn=e[2],e=e[3],null!=e?this.Nh=e:this.Nh=6,this.g=3,this.pd&&this.pd.Uv(this),this.Hv=N6(this,this.Bl()?this.zn:null,this.Mq),Mza(this)):"stop"==e[0]&&W6(this,7):3==this.g&&("stop"==e[0]?W6(this,7):"noop"!=e[0]&&this.pd&&this.pd.Tv(this,e),this.Qi=0)}}};
g.h.kO=function(){null!=this.Ph&&(this.Ph=null,this.qc.cancel(),this.qc=null,V6(this),F6())};
g.h.qo=function(a){if(this.qc==a){T6(this);this.qc=null;var b=2}else if(this.Od==a)this.Od=null,b=1;else return;this.af=a.Lk;if(0!=this.g)if(a.sf)1==b?((0,g.F)(),X6.dispatchEvent(new Dza(X6,a.Ai?a.Ai.length:0)),S6(this),this.B.length=0):Mza(this);else{var c=a.ai,d;if(!(d=3==c||7==c||0==c&&0<this.af)){if(d=1==b)this.Od||this.bh||1==this.g||2<=this.zk?d=!1:(this.bh=K6((0,g.z)(this.eB,this,a),Nza(this,this.zk)),this.zk++,d=!0);d=!(d||2==b&&V6(this))}if(d)switch(c){case 1:W6(this,5);break;case 4:W6(this,
10);break;case 3:W6(this,6);break;case 7:W6(this,12);break;default:W6(this,2)}}};
g.h.eH=function(a){if(!g.kb(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.uT=function(a){a?F6():(F6(),Oza(this,8))};
g.h.lq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.bx;a.G=!1;return a};
g.h.isActive=function(){return!!this.pd&&this.pd.isActive(this)};
g.h.nf=function(){X6.dispatchEvent(new Eza(X6))};
g.h.Bl=function(){return!(!g.vd||g.rc(10))};
g.h=Pza.prototype;g.h.Uv=function(){};
g.h.Tv=function(){};
g.h.Sv=function(){};
g.h.Zp=function(){};
g.h.Qw=function(){return{}};
g.h.isActive=function(){return!0};g.A(Z6,g.L);Z6.prototype.A=function(){500<this.tc&&24E4>2*this.tc&&(this.tc*=2);this.B();this.o&&this.start()};
Z6.prototype.start=function(){g.Pt(this.g,this.tc);this.o=(0,g.F)()+this.tc};
Z6.prototype.stop=function(){this.g.stop();this.o=0};
Z6.prototype.isActive=function(){return this.g.isActive()};g.A($6,Pza);g.h=$6.prototype;g.h.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.h.Id=function(a){return this.A.Id(a)};
g.h.U=function(a,b){return this.A.U.apply(this.A,arguments)};
g.h.dispose=function(){this.J||(this.J=!0,g.We(this.A),Sza(this),g.We(this.o),this.o=null)};
g.h.ka=function(){return this.J};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.I="";this.o.stop();this.C=a||null;this.B=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new Q6("1",c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.g;e&&(e.pd=null);d.pd=this;this.g=d;e?this.g.connect(a,b,this.D,e.A,e.uj):c?this.g.connect(a,b,this.D,c.sessionId,c.arrayId):this.g.connect(a,b,this.D)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.dc(c,b);this.o.isActive()||2==(this.g?this.g.g:0)?this.F.push(c):a7(this)&&Jza(this.g,c)};
g.h.Uv=function(){Y6(this.o);this.C=null;this.B=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)Jza(this.g,a[b])}this.U("handlerOpened")};
g.h.Sv=function(a,b){var c=2==b&&401==this.g.af;if(4!=b&&!c){if(6==b||410==this.g.af)c=this.o,c.g.stop(),c.tc=500;this.o.start()}this.U("handlerError",b)};
g.h.Zp=function(a,b,c){if(!this.o.isActive())this.U("handlerClosed");else if(c)for(a=0,b=c.length;a<b;++a){var d=c[a].map;d&&this.F.push(d)}};
g.h.Qw=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.B&&(a.ui=""+this.B);0!=this.G&&(a.ui=""+this.G);this.C&&g.dc(a,this.C);return a};
g.h.Tv=function(a,b){"S"==b[0]?this.I=b[1]:"gracefulReconnect"==b[0]?(Y6(this.o),this.o.start(),Hza(this.g)):this.U("handlerMessage",new Qza(b[0],b[1]))};
g.h.XT=function(){this.o.isActive();var a=this.g,b=0;a.qc&&b++;a.Od&&b++;0!=b?this.o.start():this.connect(this.C,this.B)};b7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
b7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
b7.prototype.C=function(a){a(Error("request timed out"))};var $za=(0,g.F)(),e7=null,h7=Array(50),g7=-1,i7=!1;g.A(j7,g.QF);j7.prototype.fe=function(){return this.g};
j7.prototype.contains=function(a){return!!l6(this.g,a)};
j7.prototype.get=function(a){return a?m6(this.g,a):null};
j7.prototype.info=function(a){f7(this.F,a)};g.A(k7,g.QF);var hBa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=k7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Aa)&&this.aD()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Aa)||(g.oE(this.Aa),this.Aa=window.NaN)};
g.h.X=function(){this.stop();k7.Z.X.call(this)};
g.h.aD=function(){this.Aa=window.NaN;this.g=g.CE(c7(this.D,"/pairing/get_screen"),{method:"POST",Ob:{pairing_code:this.C},timeout:5E3,Fb:(0,g.z)(this.aU,this),onError:(0,g.z)(this.ZT,this),sd:(0,g.z)(this.bU,this)})};
g.h.aU=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.U("pairingComplete",new g6(c))};
g.h.ZT=function(a){this.g=null;a.status&&404==a.status?this.o>=hBa.length?this.U("pairingFailed",Error("DIAL polling timed out")):(a=hBa[this.o],this.Aa=g.mE((0,g.z)(this.aD,this),a),this.o++):this.U("pairingFailed",Error("Server error "+a.status))};
g.h.bU=function(){this.g=null;this.U("pairingFailed",Error("Server not responding"))};g.A(m7,j7);g.h=m7.prototype;g.h.start=function(){l7(this)&&this.U("screenChange");!g.MG("yt-remote-lounge-token-expiration")&&dAa(this);g.oE(this.o);this.o=g.mE((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){l7(this);aAa(this,a);n7(this,!1);this.U("screenChange");b(a);a.token||dAa(this)};
g.h.remove=function(a,b){var c=l7(this);cAa(this,a)&&(n7(this,!1),c=!0);b(a);c&&this.U("screenChange")};
g.h.bp=function(a,b,c,d){var e=l7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,n7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.U("screenChange")};
g.h.X=function(){g.oE(this.o);m7.Z.X.call(this)};
g.h.LH=function(a){l7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}n7(this,!b);b&&f7(this.F,"Missed "+b+" lounge tokens.")};
g.h.KH=function(a){f7(this.F,"Requesting lounge tokens failed: "+a)};g.A(p7,g.QF);g.h=p7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.MG("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.F)()-144E5<a?0:a)?r7(this):(this.B=(0,g.F)()+3E5,g.LG("yt-remote-fast-check-period",this.B),this.zt())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){o7("Updating availability on schedule.");var a=this.D(),b=g.Mb(this.g,function(b,d){return b&&!!m6(a,d)},this);
q7(this,b)};
g.h.X=function(){g.oE(this.A);this.A=window.NaN;this.o&&(this.o.abort(),this.o=null);p7.Z.X.call(this)};
g.h.zt=function(){g.oE(this.A);this.A=window.NaN;this.o&&this.o.abort();var a=gAa(this);if(g.Pb(a)){var b=c7(this.C,"/pairing/get_screen_availability");this.o=d7(this.C,b,{lounge_token:g.Sb(a).join(",")},(0,g.z)(this.hR,this,a),(0,g.z)(this.gR,this))}else q7(this,{}),r7(this)};
g.h.hR=function(a,b){this.o=null;var c=g.Sb(gAa(this));if(g.Fb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;q7(this,d);r7(this)}else this.ac("Changing Screen set during request."),this.zt()};
g.h.gR=function(a){this.ac("Screen availability failed: "+a);this.o=null;r7(this)};
g.h.ac=function(a){f7("OnlineScreenService",a)};g.A(s7,j7);g.h=s7.prototype;g.h.start=function(){this.A.start();this.o.start();this.g.length&&(this.U("screenChange"),this.o.isEmpty()||this.U("onlineScreenChange"))};
g.h.add=function(a,b,c){this.A.add(a,b,c)};
g.h.remove=function(a,b,c){this.A.remove(a,b,c);this.o.update()};
g.h.bp=function(a,b,c,d){this.A.contains(a)?this.A.bp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,f7(this.F,a),d(Error(a)))};
g.h.fe=function(a){return a?this.g:g.ub(this.g,(0,g.Jd)(this.B,function(a){return!this.contains(a)},this))};
g.h.cD=function(){return(0,g.Jd)(this.fe(!0),function(a){return!!this.o.g[a.id]},this)};
g.h.dD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new k7(this.D,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.We(f);d(t7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.We(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.dU=function(a,b,c,d){g.CE(c7(this.D,"/pairing/get_screen"),{method:"POST",Ob:{pairing_code:a},timeout:5E3,Fb:(0,g.z)(function(a,d){var e=new g6(d.screen||{});if(!e.name||kAa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);kAa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(t7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
sd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.We(this.A);g.We(this.o);s7.Z.X.call(this)};
g.h.XH=function(){lAa(this);this.U("screenChange");this.o.update()};
s7.prototype.dispose=s7.prototype.dispose;g.A(v7,g.QF);g.h=v7.prototype;g.h.ro=function(a){this.A=a;this.U("sessionScreen",this.A)};
g.h.ke=function(a){this.ka()||(a&&w7(this,""+a),this.A=null,this.U("sessionScreen",null))};
g.h.info=function(a){f7(this.N,a)};
g.h.fD=function(){return null};
g.h.Gt=function(a){var b=this.o;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){w7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Gt("");v7.Z.X.call(this)};g.A(x7,v7);g.h=x7.prototype;g.h.Ft=function(a){if(this.g){if(this.g==a)return;w7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.D);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.C)}this.g=a;this.g.addUpdateListener(this.D);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.C);nAa(this)};
g.h.vj=function(a){this.info("launchWithParams no-op for Cast: "+g.xg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.ke()},this),(0,g.z)(function(){this.ke(Error("Failed to stop receiver app."))},this)):this.ke(Error("Stopping cast device witout session."))};
g.h.Gt=g.y;g.h.X=function(){this.info("disposeInternal");g.oE(this.B);this.B=0;this.g&&(this.g.removeUpdateListener(this.D),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.C));this.g=null;x7.Z.X.call(this)};
g.h.iS=function(a,b){if(!this.ka())if(b){var c=g.Ww(b);if(c){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.xg(c));switch(d){case "mdxSessionStatus":mAa(this,c.screenId);break;default:w7(this,"Unknown youtube message: "+d)}}else w7(this,"Unable to parse message.")}else w7(this,"No data in message.")};
g.h.fx=function(a,b,c,d){jAa(this.I,this.o.label,a,this.o.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(w7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.mE((0,g.z)(this.fx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.fD=function(){return this.g};
g.h.eU=function(a){this.ka()||a||(w7(this,"Cast session died."),this.ke())};g.A(y7,v7);g.h=y7.prototype;g.h.Ft=function(a){this.B=a;this.B.addUpdateListener(this.L)};
g.h.vj=function(a){this.C=a;this.F()};
g.h.stop=function(){this.g();this.g=g.y;g.oE(this.D);this.B?this.B.stop((0,g.z)(this.ke,this,null),(0,g.z)(this.ke,this,"Failed to stop DIAL device.")):this.ke()};
g.h.X=function(){this.g();this.g=g.y;g.oE(this.D);this.B&&this.B.removeUpdateListener(this.L);this.B=null;y7.Z.X.call(this)};
g.h.hU=function(a){this.ka()||a||(w7(this,"DIAL session died."),this.g(),this.g=g.y,this.ke())};
g.h.Cr=function(a){this.J=k6();if(this.C){var b=new window.chrome.cast.DialLaunchResponse(!0,pAa(this));a(b);oAa(this)}else this.F=(0,g.z)(function(){g.oE(this.D);this.F=g.y;this.D=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,pAa(this));a(b);oAa(this)},this),this.D=g.mE((0,g.z)(function(){this.F()},this),100)};
g.h.yJ=function(a,b){jAa(this.I,this.G.receiver.label,a,this.o.friendlyName,(0,g.z)(function(a){a&&a.token?(this.ro(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Cr(b)},this),(0,g.z)(function(a){w7(this,"Failed to get DIAL screen: "+a);
this.Cr(b)},this))};g.A(z7,v7);z7.prototype.stop=function(){this.ke()};
z7.prototype.Ft=g.y;z7.prototype.vj=function(){g.oE(this.g);this.g=window.NaN;var a=m6(this.I.fe(),this.o.label);a?this.ro(a):this.ke(Error("No such screen"))};
z7.prototype.X=function(){g.oE(this.g);this.g=window.NaN;z7.Z.X.call(this)};g.A(A7,g.QF);g.h=A7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.aB,this),(0,g.z)(this.SQ,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.VO,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ka()||(window.chrome.cast.addReceiverActionListener(this.B),Xza(),this.o.subscribe("onlineScreenChange",(0,g.z)(this.eD,this)),this.A=rAa(this),window.chrome.cast.setCustomReceivers(this.A,g.y,(0,g.z)(function(a){this.ac("Failed to set initial custom receivers: "+g.xg(a))},this)),this.U("yt-remote-cast2-availability-change",C7(this)),b(!0))},this),(0,g.z)(function(a){this.ac("Failed to initialize API: "+g.xg(a));
b(!1)},this))};
g.h.fT=function(a,b){B7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.A;if(!a||c&&c.id!=a)B7("Unsetting old screen status: "+this.g.o.friendlyName),D7(this,null)}if(a&&b){if(!this.g){c=m6(this.o.fe(),a);if(!c){B7("setConnectedScreenStatus: Unknown screen.");return}var d=qAa(this,c);d||(B7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.A.push(d),
window.chrome.cast.setCustomReceivers(this.A,g.y,(0,g.z)(function(a){this.ac("Failed to set initial custom receivers: "+g.xg(a))},this)));
B7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);D7(this,new z7(this.o,d),!0)}this.g.Gt(b)}else B7("setConnectedScreenStatus: no screen.")};
g.h.gT=function(a){this.ka()?this.ac("Setting connection data on disposed cast v2"):this.g?this.g.vj(a):this.ac("Setting connection data without a session")};
g.h.gU=function(){this.ka()?this.ac("Stopping session on disposed cast v2"):this.g?(this.g.stop(),D7(this,null)):B7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.aB,this),(0,g.z)(this.lR,this))};
g.h.X=function(){this.o.unsubscribe("onlineScreenChange",(0,g.z)(this.eD,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.B);g.sb(g.x("yt.mdx.remote.debug.handlers_")||[],Uza);g.We(this.g);A7.Z.X.call(this)};
g.h.ac=function(a){f7("Controller",a)};
g.h.bB=function(a,b){this.g==a&&(b||D7(this,null),this.U("yt-remote-cast2-session-change",b))};
g.h.OQ=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),B7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.o.label!=a.label)B7("onReceiverAction_: Stopping active receiver: "+this.g.o.friendlyName),this.g.stop();else{B7("onReceiverAction_: Casting to active receiver.");this.g.A&&this.U("yt-remote-cast2-session-change",this.g.A);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:D7(this,
new z7(this.o,a));break;case window.chrome.cast.ReceiverType.DIAL:D7(this,new y7(this.o,a,this.D));break;case window.chrome.cast.ReceiverType.CAST:D7(this,new x7(this.o,a));break;default:this.ac("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.o.label==a.label?this.g.stop():this.ac("Stopping receiver w/o session: "+a.friendlyName)}else this.ac("onReceiverAction_ called without receiver.")};
g.h.VO=function(a){if(this.ka())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.ac("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.o:null;if(!c||c.label!=b.label)return this.ac("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.A)return B7("Reselecting dial screen."),
this.U("yt-remote-cast2-session-change",this.g.A),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.ac('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);D7(this,new y7(this.o,b,this.D))}b=this.g;b.G=a;return b.G.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.yJ,b,(b.G.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.Cr,b))};
g.h.aB=function(a){if(!this.ka()){B7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)B7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),D7(this,new x7(this.o,b),!0);else{this.ac("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.o,d=m6(this.o.fe(),c.label);
d&&h6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(B7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.We(this.g),this.g=new x7(this.o,b),this.g.subscribe("sessionScreen",(0,g.z)(this.bB,this,this.g)),this.g.vj(null));this.g.Ft(a)}}};
g.h.fU=function(){return this.g?this.g.fD():null};
g.h.lR=function(a){this.ka()||(this.ac("Failed to estabilish a session: "+g.xg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&D7(this,null))};
g.h.SQ=function(a){B7("Receiver availability updated: "+a);if(!this.ka()){var b=C7(this);this.C=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;C7(this)!=b&&this.U("yt-remote-cast2-availability-change",C7(this))}};
g.h.eD=function(){this.ka()||(this.A=rAa(this),B7("Updating custom receivers: "+g.xg(this.A)),window.chrome.cast.setCustomReceivers(this.A,g.y,(0,g.z)(function(){this.ac("Failed to set custom receivers.")},this)),this.U("yt-remote-cast2-availability-change",C7(this)))};
A7.prototype.setLaunchParams=A7.prototype.gT;A7.prototype.setConnectedScreenStatus=A7.prototype.fT;A7.prototype.stopSession=A7.prototype.gU;A7.prototype.getCastSession=A7.prototype.fU;A7.prototype.requestSession=A7.prototype.requestSession;A7.prototype.init=A7.prototype.init;A7.prototype.dispose=A7.prototype.dispose;var J7=[];O7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";P7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.If=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.I=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!(0,window.isNaN)(this.B))};
O7.prototype.jb=function(){return 1==this.g};
O7.prototype.getDuration=function(){return this.D?this.I+Q7(this):this.I};
O7.prototype.clone=function(){return new O7(U7(this))};g.A(W7,g.QF);g.h=W7.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,c8(this,"play")):a8(this,"play"),$7(this,1,S7(X7(this))),this.U("remotePlayerChange")):Y7(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,c8(this,"pause")):a8(this,"pause"),$7(this,2,S7(X7(this))),this.U("remotePlayerChange")):Y7(this,this.pause)};
g.h.ZC=function(a){if(1==this.g){if(this.o){var b=X7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.jb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,c8(this,"seekTo",{newTime:a}))}else a8(this,"seekTo",{newTime:a});$7(this,3,a);this.U("remotePlayerChange")}else Y7(this,g.Da(this.ZC,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,c8(this,"stopVideo")):a8(this,"stopVideo");var a=X7(this);a.index=-1;a.videoId="";P7(a);Z7(this,a);this.U("remotePlayerChange")}else Y7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=X7(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){b8("set receiver volume: "+d)},this),(0,g.z)(function(){this.ac("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){b8("set receiver muted: "+b)},this),(0,g.z)(function(){this.ac("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);a8(this,"setVolume",e)}c.muted=b;c.volume=a;Z7(this,c)}else Y7(this,g.Da(this.setVolume,a,b))};
g.h.eC=function(a,b){if(1==this.g){var c=X7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.xg(b.style),g.dc(d,c.o));a8(this,"setSubtitlesTrack",d);Z7(this,c)}else Y7(this,g.Da(this.eC,a,b))};
g.h.ru=function(a,b){if(1==this.g){a8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Rc.id});var c=X7(this);c.audioTrackId=b.Rc.id;Z7(this,c)}else Y7(this,g.Da(this.ru,a,b))};
g.h.YC=function(a,b){if(1==this.g){if(a&&b){var c=X7(this);T7(c,a,b);Z7(this,c)}a8(this,"previous")}else Y7(this,g.Da(this.YC,a,b))};
g.h.XC=function(a,b){if(1==this.g){if(a&&b){var c=X7(this);T7(c,a,b);Z7(this,c)}a8(this,"next")}else Y7(this,g.Da(this.XC,a,b))};
g.h.xw=function(){1==this.g?a8(this,"dismissAutoplay"):Y7(this,this.xw)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}W7.Z.dispose.call(this)};
g.h.X=function(){DAa(this);this.B=null;this.C.clear();V7(this,null);W7.Z.X.call(this)};
g.h.tu=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.cC(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.KQ=function(a,b){this.U(a,b)};
g.h.rO=function(a){if(!a)this.sl(null),V7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=X7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)b8("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,Z7(this,b)}};
g.h.sl=function(a){b8("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),EAa(this),this.U("remotePlayerChange")};
g.h.qO=function(a){a?(EAa(this),this.U("remotePlayerChange")):this.sl(null)};
g.h.EO=function(){var a=AAa();a&&V7(this,a)};
g.h.ac=function(a){f7("CP",a)};g.A(d8,g.QF);g.h=d8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.bb.listId=c);this.bb.videoId=d;this.bb.index=k||0;this.bb.state=3;R7(this.bb,m);this.B="UNSUPPORTED";e8("Connecting with setPlaylist and params: "+g.xg(l));this.g.connect({method:"setPlaylist",params:g.xg(l)},a,Zya())}else e8("Connecting without params"),
this.g.connect({},a,Zya());GAa(this)};
g.h.dispose=function(){this.ka()||(this.U("beforeDispose"),f8(this,3));d8.Z.dispose.call(this)};
g.h.X=function(){g8(this);i8(this);h8(this);g.oE(this.I);this.I=window.NaN;g.oE(this.J);this.J=window.NaN;this.A=null;g.CF(this.T);this.T.length=0;this.g.dispose();d8.Z.X.call(this);this.B=this.F=this.o=this.bb=this.g=null};
g.h.CH=function(){this.D(2)};
g.h.vO=function(){e8("Channel opened");this.O&&(this.O=!1,h8(this),this.N=g.mE((0,g.z)(function(){e8("Timing out waiting for a screen.");this.D(1)},this),15E3));
cza(Rza(this.g),this.aa)};
g.h.sO=function(){e8("Channel closed");(0,window.isNaN)(this.C)?r6(!0):r6();this.dispose()};
g.h.tO=function(a){r6();(0,window.isNaN)(this.G())?(e8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,e8("Channel error: "+a+" with reconnection in "+this.G()+" ms"),f8(this,2))};
g.h.uO=function(a){a.params?e8("Received: action="+a.action+", params="+g.xg(a.params)):e8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Ww(a.params.devices);this.o=(0,g.H)(a,function(a){return new f6(a)});
a=!!g.fb(this.o,function(a){return"LOUNGE_SCREEN"==a.type});
JAa(this,a);break;case "loungeScreenDisconnected":g.tb(this.o,function(a){return"LOUNGE_SCREEN"==a.type});
JAa(this,!1);break;case "remoteConnected":var b=new f6(g.Ww(a.params.device));g.fb(this.o,function(a){return b?a.id==b.id:!1})||g.qb(this.o,b);
break;case "remoteDisconnected":b=new f6(g.Ww(a.params.device));g.tb(this.o,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":LAa(this,a);break;case "nowPlaying":NAa(this,a);break;case "onStateChange":MAa(this,a);break;case "onAdStateChange":OAa(this,a);break;case "onVolumeChanged":PAa(this,a);break;case "onSubtitlesTrackChanged":KAa(this,a);break;case "nowAutoplaying":QAa(this,a);break;case "autoplayDismissed":this.U("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.U("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.U("autoplayModeChange",this.B);"DISABLED"==this.B&&this.U("autoplayDismissed");break;case "onHasPreviousNextChanged":RAa(this,a);break;case "requestAssistedSignIn":this.U("assistedSignInRequested",a.params.authCode);break;default:e8("Unrecognized action: "+a.action)}};
g.h.RS=function(){if(this.A){var a=this.A;this.A=null;this.bb.videoId!=a&&j8(this,"getNowPlaying")}};
d8.prototype.subscribe=d8.prototype.subscribe;d8.prototype.unsubscribeByKey=d8.prototype.Id;d8.prototype.fa=function(){var a=3;this.ka()||(a=0,(0,window.isNaN)(this.G())?a7(this.g)&&(0,window.isNaN)(this.C)&&(a=1):a=2);return a};
d8.prototype.getProxyState=d8.prototype.fa;d8.prototype.D=function(a){e8("Disconnecting with "+a);g8(this);this.U("beforeDisconnect",a);1==a&&r6();Sza(this.g,a);this.dispose()};
d8.prototype.disconnect=d8.prototype.D;d8.prototype.ea=function(){var a=this.bb;this.A&&(a=this.bb.clone(),T7(a,this.A,a.index));return U7(a)};
d8.prototype.getPlayerContextData=d8.prototype.ea;
d8.prototype.ma=function(a){var b=new O7(a);b.videoId&&b.videoId!=this.bb.videoId&&(this.A=b.videoId,g.oE(this.I),this.I=g.mE((0,g.z)(this.RS,this),5E3));var c=[];this.bb.listId==b.listId&&this.bb.videoId==b.videoId&&this.bb.index==b.index||c.push("remoteQueueChange");this.bb.g==b.g&&this.bb.volume==b.volume&&this.bb.muted==b.muted&&S7(this.bb)==S7(b)&&g.xg(this.bb.o)==g.xg(b.o)||c.push("remotePlayerChange");this.bb.reset(a);(0,g.G)(c,function(a){this.U(a)},this)};
d8.prototype.setPlayerContextData=d8.prototype.ma;d8.prototype.Y=function(){var a=this.g.D.id,b=g.fb(this.o,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
d8.prototype.getOtherConnectedRemoteId=d8.prototype.Y;d8.prototype.G=function(){var a=this.g;return a.o.isActive()?a.o.o-(0,g.F)():window.NaN};
d8.prototype.getReconnectTimeout=d8.prototype.G;d8.prototype.ba=function(){return this.B||"UNSUPPORTED"};
d8.prototype.getAutoplayMode=d8.prototype.ba;d8.prototype.da=function(){return this.F||""};
d8.prototype.getAutoplayVideoId=d8.prototype.da;d8.prototype.pa=function(){if(!(0,window.isNaN)(this.G())){var a=this.g.o;g.Qt(a.g);a.start()}};
d8.prototype.reconnect=d8.prototype.pa;d8.prototype.ia=function(a,b){j8(this,a,b);IAa(this)};
d8.prototype.sendMessage=d8.prototype.ia;g.A(k8,j7);g.h=k8.prototype;g.h.fe=function(a){return this.bd.$_gs(a)};
g.h.contains=function(a){return!!this.bd.$_c(a)};
g.h.get=function(a){return this.bd.$_g(a)};
g.h.start=function(){this.bd.$_st()};
g.h.add=function(a,b,c){this.bd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.bd.$_r(a,b,c)};
g.h.bp=function(a,b,c,d){this.bd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.bd.$_ubk(this.o[a]);this.o.length=0;this.bd=null;k8.Z.X.call(this)};
g.h.cU=function(){this.U("screenChange")};
g.h.qQ=function(){this.U("onlineScreenChange")};
s7.prototype.$_st=s7.prototype.start;s7.prototype.$_gspc=s7.prototype.dU;s7.prototype.$_gsppc=s7.prototype.dD;s7.prototype.$_c=s7.prototype.contains;s7.prototype.$_g=s7.prototype.get;s7.prototype.$_a=s7.prototype.add;s7.prototype.$_un=s7.prototype.bp;s7.prototype.$_r=s7.prototype.remove;s7.prototype.$_gs=s7.prototype.fe;s7.prototype.$_gos=s7.prototype.cD;s7.prototype.$_s=s7.prototype.subscribe;s7.prototype.$_ubk=s7.prototype.Id;var l8=null,m8=null,B8=null,q8=[];g.p(C8,g.L);g.h=C8.prototype;
g.h.X=function(){g.L.prototype.X.call(this);this.A.stop();this.B.stop();this.J.stop();this.N();this.g.unsubscribe("proxyStateChange",this.YA,this);this.g.unsubscribe("remotePlayerChange",this.ul,this);this.g.unsubscribe("remoteQueueChange",this.so,this);this.g.unsubscribe("autoplayUpNext",this.xA,this);this.g.unsubscribe("previousNextChange",this.VA,this);this.g.unsubscribe("nowAutoplaying",this.NA,this);this.g.unsubscribe("autoplayDismissed",this.wA,this);this.g=this.F=null};
g.h.fz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(a9(this)){if(1081!=X7(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":X7(this.g).jb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.ej(c[0],c[1]);break;case "control_subtitles_set_track":b9(this,c[0]);break;case "control_set_audio_track":c=c[0],a9(this)&&this.g.ru(this.R.ga(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.R.getCurrentTime();j9(this,0==c?void 0:c);break;case "control_seek":j9(this,c[0]);break;case "control_subtitles_set_track":b9(this,c[0]);break;case "control_set_audio_track":c=c[0],a9(this)&&this.g.ru(this.R.ga(1).videoId,c)}};
g.h.pO=function(a){this.J.yH(a)};
g.h.CT=function(a){this.fz("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.sC=function(){var a=this.R.yc("captions","track");g.Yb(a)||b9(this,a)};
g.h.LA=function(a){if(a9(this)){this.g.unsubscribe("remotePlayerChange",this.ul,this);var b=Math.round(a.volume);a=!!a.muted;var c=X7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.L.start();this.g.subscribe("remotePlayerChange",this.ul,this)}};
g.h.JP=function(){g.Yb(this.C)||cBa(this,this.C);this.D=!1};
g.h.YA=function(a,b){this.B.stop();2==b&&this.oC()};
g.h.ul=function(){if(a9(this)){this.A.stop();var a=X7(this.g);switch(a.g){case 1081:case 1:P8(this,new g.yO(8));this.nC();break;case 1085:case 3:P8(this,new g.yO(9));break;case 1083:case 0:P8(this,new g.yO(2));this.I.stop();D8(this,this.R.ga().lengthSeconds);break;case 1084:P8(this,new g.yO(4));break;case 2:P8(this,new g.yO(4));D8(this,S7(a));break;case -1:P8(this,new g.yO(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},P8(this,new g.yO(128,a))}a=X7(this.g).o;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,cBa(this,a));a=X7(this.g);-1==a.volume||Math.round(this.R.getVolume())==a.volume&&this.R.isMuted()==a.muted||this.L.isActive()||this.QC()}else bBa(this)};
g.h.VA=function(){this.R.U("mdxpreviousnextchange")};
g.h.so=function(){a9(this)||bBa(this)};
g.h.GG=function(){this.g.xw()};
g.h.xA=function(a){a&&(a=g.CE("/watch_queue_ajax",{method:"GET",Yc:{action_get_watch_queue_item:1,video_id:a},Fb:(0,g.z)(this.KR,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.KR=function(a,b){var c=new g.zN({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.R.U("mdxautoplayupnext",c)};
g.h.NA=function(a){(0,window.isNaN)(a)||this.R.U("mdxnowautoplaying",a)};
g.h.wA=function(){this.R.U("mdxautoplaycanceled")};
g.h.aL=function(a,b){-1==X7(this.g).g?j9(this,a):b&&this.g.ZC(a)};
g.h.QC=function(){if(a9(this)){var a=X7(this.g);this.o.Ea(this.O);a.muted?this.R.mute():this.R.Tf();this.R.setVolume(a.volume);this.O=this.o.P(this.R,"onVolumeChange",this.LA)}};
g.h.nC=function(){this.A.stop();if(!this.g.ka()){var a=X7(this.g);a.jb()&&P8(this,new g.yO(8));D8(this,S7(a));this.A.start()}};
g.h.oC=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(m9,g.Y);m9.prototype.B=function(a){eBa(this,a.state)};g.p(n9,g.e_);n9.prototype.I=function(){var a=this.R.yc("remote","receivers");a&&1<a.length&&!this.R.yc("remote","quickCast")?(this.F=g.Hb(a,this.B,this),g.f_(this,(0,g.H)(a,this.B)),a=this.R.yc("remote","currentReceiver"),this.mf(this.B(a)),this.enable(!0)):this.enable(!1)};
n9.prototype.B=function(a){return a.key};
n9.prototype.lf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
n9.prototype.rd=function(a){g.e_.prototype.rd.call(this,a);this.R.Gd("remote","currentReceiver",this.F[a]);this.A.Nb()};g.p(o9,g.xV);g.h=o9.prototype;g.h.create=function(){WAa(g.TL(g.X(this.g)));this.D.push(g.cG("yt-remote-before-disconnect",this.lO,this));this.D.push(g.cG("yt-remote-connection-change",this.TQ,this));this.D.push(g.cG("yt-remote-receiver-availability-change",this.WA,this));this.D.push(g.cG("yt-remote-auto-connect",this.RQ,this));this.D.push(g.cG("yt-remote-receiver-resumed",this.QQ,this));this.WA()};
g.h.load=function(){this.g.Vp();g.xV.prototype.load.call(this);this.C=new C8(this,this.g,this.o);var a=(a=aBa())?a.currentTime:0;var b=A8()?new W7(v8(),void 0):null;0==a&&b&&(a=S7(X7(b)));0!=a&&(this.I=a||0,this.g.U("progresssync",a,void 0));dBa(this,this.F,this.F);g.$_(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.Xe(this.C,this.o);this.o=this.C=null;g.xV.prototype.unload.call(this);g.$_(this.g.app,5)};
g.h.X=function(){g.dG(this.D);g.xV.prototype.X.call(this)};
g.h.Yk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.fz.apply(this.C,[].concat([a],g.pa(c)))};
g.h.tH=function(){return this.loaded?this.C.suggestion:null};
g.h.If=function(){return this.o?X7(this.o).If:!1};
g.h.hasNext=function(){return this.o?X7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.DK=function(){var a=X7(this.o),b=this.g.ga();return{allowSeeking:this.g.cd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+Q7(a):a.B,isPeggedToLive:1>=(a.D?a.A+Q7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+Q7(a):a.A,seekableStart:0<a.C?a.C+Q7(a):a.C}};
g.h.EK=function(){this.o&&this.o.XC()};
g.h.FK=function(){this.o&&this.o.YC()};
g.h.lO=function(a){1==a&&(this.J=this.o?X7(this.o):null)};
g.h.TQ=function(){var a=A8()?new W7(v8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.We(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.ga().videoId&&this.g.mz(a.videoId,S7(a)));this.g.U("videodatachange","newdata",this.g.ga(),3)};
g.h.WA=function(){this.G=[this.A].concat(YAa());var a=w8()||this.A;p9(this,a);this.g.va("onMdxReceiversChange")};
g.h.RQ=function(){var a=w8();p9(this,a)};
g.h.QQ=function(){this.B=w8()};
g.h.CK=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?M7():p9(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&M7(),!0):!1}};
g.h.GK=function(){a8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.ud=function(){return!1};g.iY.remote=o9;})(_yt_player);
